# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataLoad.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadDataWindow(object):
    def setupUi(self, LoadDataWindow):
        LoadDataWindow.setObjectName("LoadDataWindow")
        LoadDataWindow.resize(420, 140)
        LoadDataWindow.setMinimumSize(QtCore.QSize(420, 140))
        LoadDataWindow.setMaximumSize(QtCore.QSize(420, 140))
        self.verticalLayoutWidget = QtWidgets.QWidget(LoadDataWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 421, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeDiapazonTSA_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.timeDiapazonTSA_2.setMaximumSize(QtCore.QSize(489, 80))
        self.timeDiapazonTSA_2.setObjectName("timeDiapazonTSA_2")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.timeDiapazonTSA_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(3, 13, 411, 61))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.fromDateTimeTSA_3 = QtWidgets.QDateTimeEdit(self.gridLayoutWidget_6)
        self.fromDateTimeTSA_3.setObjectName("fromDateTimeTSA_3")
        self.gridLayout_6.addWidget(self.fromDateTimeTSA_3, 1, 0, 1, 1)
        self.toDateTimeTSA_3 = QtWidgets.QDateTimeEdit(self.gridLayoutWidget_6)
        self.toDateTimeTSA_3.setObjectName("toDateTimeTSA_3")
        self.gridLayout_6.addWidget(self.toDateTimeTSA_3, 1, 1, 1, 1)
        self.endDateLabelTSA_3 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.endDateLabelTSA_3.setObjectName("endDateLabelTSA_3")
        self.gridLayout_6.addWidget(self.endDateLabelTSA_3, 0, 1, 1, 1)
        self.startDateLabelTSA_3 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.startDateLabelTSA_3.setObjectName("startDateLabelTSA_3")
        self.gridLayout_6.addWidget(self.startDateLabelTSA_3, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.timeDiapazonTSA_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.loadButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout.addWidget(self.loadButton)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(LoadDataWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadDataWindow)

    def retranslateUi(self, LoadDataWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadDataWindow.setWindowTitle(_translate("LoadDataWindow", "LoadDataWindow"))
        self.timeDiapazonTSA_2.setTitle(_translate("LoadDataWindow", "Выбор временного диапазона"))
        self.endDateLabelTSA_3.setText(_translate("LoadDataWindow", "Конечная дата"))
        self.startDateLabelTSA_3.setText(_translate("LoadDataWindow", "Начальная дата"))
        self.loadButton.setText(_translate("LoadDataWindow", "Загрузить данные"))